### PR TITLE
fix requests block

### LINKED ISSUE #44: Init blocked in image_checker.py>connectionpool.py, while the job remains waiting.
init.log:

```
+ CHILD_PROCESS=UNKNOWN
+ trap exit_handler EXIT
+ PAI_WORK_DIR=/usr/local/pai
+ PAI_CONFIG_DIR=/usr/local/pai-config
+ PAI_INIT_DIR=/usr/local/pai/init.d
+ PAI_RUNTIME_DIR=/usr/local/pai/runtime.d
+ PAI_LOG_DIR=/usr/local/pai/logs/a1333840-bc83-4844-b34d-a514d3ecb2e6
+ PAI_SECRET_DIR=/usr/local/pai/secrets
+ PAI_USER_EXTENSION_SECRET_DIR=/usr/local/pai/user-extension-secrets
+ PAI_TOKEN_SECRET_DIR=/usr/local/pai/token-secrets
+ chmod a+rw /usr/local/pai/logs/a1333840-bc83-4844-b34d-a514d3ecb2e6
+ find /usr/local/pai/logs/a1333840-bc83-4844-b34d-a514d3ecb2e6 -maxdepth 1 -type f '!' -name init.log
+ LOG_FILES=
+ '[[' '!' -z  ]]
+ find /usr/local/pai -maxdepth 1 -mindepth 1 '!' -name logs -exec rm -rf '{}' ';'
rm: can't remove '/usr/local/pai/user-extension-secrets/..data': Read-only file system
rm: can't remove '/usr/local/pai/user-extension-secrets/userExtensionSecrets.yaml': Read-only file system
rm: can't remove '/usr/local/pai/user-extension-secrets/..2021_10_31_09_21_19.825915050/userExtensionSecrets.yaml': Read-only file system
+ mv ./__init__.py ./common ./init ./init.d ./package_cache ./plugins ./requirements.txt ./runtime ./runtime.d /usr/local/pai
+ cd /usr/local/pai
+ '[[' true '=' true ]]
+ CHILD_PROCESS=FRAMEWORK_BARRIER
+ echo 'frameworkbarrier start'
frameworkbarrier start
+ '[[' -f /var/run/secrets/kubernetes.io/serviceaccount/token ]]
+ unset KUBE_APISERVER_ADDRESS
+ /usr/local/pai/init.d/frameworkbarrier
+ tee /usr/local/pai/logs/a1333840-bc83-4844-b34d-a514d3ecb2e6/barrier.log
I1031 09:21:22.909826      15 barrier.go:211] Initializing frameworkbarrier
I1031 09:21:22.910057      15 barrier.go:214] With Config: 
kubeApiServerAddress: ""
kubeConfigFilePath: ""
frameworkNamespace: default
frameworkName: c584ad33319d4553e4054ab6777cf38d
barrierCheckIntervalSec: 10
barrierCheckTimeoutSec: 600
W1031 09:21:22.910094      15 client_config.go:549] Neither --kubeconfig nor --master was specified.  Using the inClusterConfig.  This might not work.
I1031 09:21:22.911898      15 barrier.go:227] Running frameworkbarrier
I1031 09:21:22.934270      15 barrier.go:322] BarrierPassed: 1/1 Tasks are ready with not nil PodIP.
I1031 09:21:22.934299      15 barrier.go:267] BarrierSucceeded: All Tasks are ready with not nil PodIP.
I1031 09:21:22.938656      15 barrier.go:350] Succeeded to dump the Framework object to local file: ./framework.json
I1031 09:21:22.938780      15 barrier.go:451] Succeeded to generate the injector script to local file: ./injector.sh
I1031 09:21:22.938962      15 barrier.go:459] ExitCode: 0: Exit with success.
+ CHILD_PROCESS=ERROR_SPEC
+ cp /usr/local/pai-config/runtime-exit-spec.yaml /usr/local/pai/runtime.d
+ CHILD_PROCESS=ENV_GENERATOR
+ python /usr/local/pai/init.d/framework_parser.py genenv framework.json
2021-10-31 09:21:23,007 - INFO - framework_parser.py:196 - loading json from framework.json
2021-10-31 09:21:23,008 - INFO - framework_parser.py:107 - task roles: {'taskrole': {'number': 1, 'ports': {'schedulePortStart': 15000, 'schedulePortEnd': 40000, 'ports': {'ssh': {'count': 1}, 'http': {'count': 1}}}}}
+ CHILD_PROCESS=CONFIG_GENERATOR
+ python /usr/local/pai/init.d/framework_parser.py genconf framework.json
2021-10-31 09:21:23,059 - INFO - framework_parser.py:196 - loading json from framework.json
+ CHILD_PROCESS=PLUGIN_INITIALIZER
+ python /usr/local/pai/init.d/initializer.py /usr/local/pai/runtime.d/job_config.yaml /usr/local/pai/secrets/secrets.yaml /usr/local/pai/user-extension-secrets/userExtensionSecrets.yaml /usr/local/pai/token-secrets/token /usr/local/pai/plugins /usr/local/pai/runtime.d taskrole
2021-10-31 09:21:23,162 - INFO - initializer.py:235 - loading yaml from /usr/local/pai/runtime.d/job_config.yaml
2021-10-31 09:21:23,170 - INFO - initializer.py:173 - Starting to prepare plugin ssh
2021-10-31 09:21:23,266 - INFO - initializer.py:52 - 2021-10-31 09:21:23,266 - INFO - init.py:118 - Ssh runtime plugin perpared
2021-10-31 09:21:23,277 - INFO - initializer.py:173 - Starting to prepare plugin teamwise_storage
2021-10-31 09:21:23,802 - INFO - initializer.py:52 - This plugin is deprecated, will ignore this plugin
+ CHILD_PROCESS=PORT_CONFLICT_CHECKER
+ python /usr/local/pai/init.d/port.py /usr/local/pai/runtime.d/runtime_env.sh
2021-10-31 09:21:23,943 - INFO - port.py:71 - runtime env from /usr/local/pai/runtime.d/runtime_env.sh
+ CHILD_PROCESS=DOCKER_IMAGE_CHECKER
+ python /usr/local/pai/init.d/image_checker.py /usr/local/pai/runtime.d/job_config.yaml /usr/local/pai/secrets/secrets.yaml
2021-10-31 09:21:24,142 - INFO - image_checker.py:266 - get job config from /usr/local/pai/runtime.d/job_config.yaml
2021-10-31 09:21:24,148 - INFO - image_checker.py:276 - Start checking docker image
2021-10-31 09:21:24,150 - DEBUG - connectionpool.py:975 - Starting new HTTPS connection (1): index.docker.io:443
2021-10-31 09:21:25,214 - DEBUG - connectionpool.py:461 - https://index.docker.io:443 "HEAD /v2/ HTTP/1.1" 401 0
2021-10-31 09:21:25,219 - DEBUG - connectionpool.py:975 - Starting new HTTPS connection (1): index.docker.io:443
2021-10-31 09:21:26,286 - DEBUG - connectionpool.py:461 - https://index.docker.io:443 "HEAD /v2/cs231666/docker/manifests/v1.1.9 HTTP/1.1" 401 0
2021-10-31 09:21:26,293 - DEBUG - connectionpool.py:975 - Starting new HTTPS connection (1): auth.docker.io:443
2021-10-31 09:21:27,348 - DEBUG - connectionpool.py:461 - https://auth.docker.io:443 "GET /token?service=registry.docker.io&scope=repository%3Acs231666%2Fdocker%3Apull HTTP/1.1" 200 None
2021-10-31 09:21:27,352 - DEBUG - connectionpool.py:975 - Starting new HTTPS connection (1): index.docker.io:443
```

It seems that `index.docker.io` returned code `401`, but this image does not require authentication. Attempting to pull the image on the host machine was successful:

image

I don't know why  `index.docker.io` returns code `401`, the issue just happened by accident. Because the authentication information was not filled in when the job was submitted, the initialization process was blocked, maybe this is a bug related to the `requests` or `urllib3` package.

For `openpai-runtime`, maybe we need to optimize the source code to handle this situation, that is when `index.docker.io` returns `401` and the authentication information is empty, return `False` immediately.

### PR DESCRIPTION
**Pull request by siaimes**
fix requests block fix #44 

Signed-off-by: siaimes <34199488+siaimes@users.noreply.github.com>

### CODE REVIEW

File: src/init.d/image_checker.py [hunk 1]
```diff
@@ -158,7 +158,7 @@ def _get_and_set_token(self, challenge) -> None:
         del parameters["realm"]
         resp = requests.get(url,
                             headers=self._basic_auth_headers,
-                            params=parameters)
+                            params=parameters, timeout=10)
```
Comment (Binyang2014) [inline src/init.d/image_checker.py:161]: Can you add a variable name `default_timeout` and let timeout equal to this?

**Review by Binyang2014 — APPROVED** [review]
Thanks for this fix, only minor comments
